TrackBug/Areas/Admin/Controllers/EmployeeTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TrackBug.DataAccess;
using TrackBug.Models;
using TrackBug.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TrackBug.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Authorize(Roles = "Admin")]
    public class EmployeeTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public EmployeeTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Product
        public async Task<IActionResult> Index()
        {
            return View(await _unitOfWork.EmployeeType.GetAllAsync());
        }

        //GET
        public IActionResult Upsert(int? id)
        {
            EmployeeType employeeType = new();


            if (id == null || id == 0)
            {
                return View(employeeType);
            }
            else
            {
                // update product
                employeeType = _unitOfWork.EmployeeType.GetFirstOrDefault(u => u.Id == id);
                return View(employeeType);
            }
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(EmployeeType obj)
        {

            if (ModelState.IsValid)
            {
                if (obj.Id == 0)
                {
                    _unitOfWork.EmployeeType.Add(obj);
                    await _unitOfWork.SaveAsync();
                    TempData["success"] = "Employee type created successfully";
                }
                else
                {
                    _unitOfWork.EmployeeType.Update(obj);
                    await _unitOfWork.SaveAsync();
                    TempData["success"] = "Employee type updated successfully";
                }

                return RedirectToAction("Index");
            }
            return View(obj);
        }

        #region API CALLS
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var employeeTypes = await _unitOfWork.EmployeeType.GetAllAsync();
            return Json(new { data = employeeTypes });
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int? id)
        {
            var obj = await _unitOfWork.EmployeeType.GetFirstOrDefaultAsync(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }


            _unitOfWork.EmployeeType.Remove(obj);
            await _unitOfWork.SaveAsync();
            return Json(new { success = true, message = "Employee type delete was successful" });

        }
        #endregion


    }
}

TrackBug/Areas/Admin/Views/EmployeeType/Index.cshtml
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Job titles List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="EmployeeType" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create Job title
            </a>
        </div>
    </div>
    <br /><br />

    <table id="tblData" class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Title</th>
               
                <th></th>
            </tr>
        </thead>
    </table>
</div>

@section Scripts{
    <script src="~/js/employeeType.js"></script>
}

TrackBug/Areas/Admin/Views/EmployeeType/Upsert.cshtml
@model TrackBug.Models.EmployeeType

<form method="post" asp-action="Upsert" enctype="multipart/form-data">
    <input asp-for="Id" hidden />

    <div class="row">
        <div class="col-10">
            <div class="border p-3 mt-4 row">
                <div class="col-12 pb-2">
                    <h2 class="text-primary">@(Model.Id!=0?"Update": "Create")  Job title</h2>
                    <hr />
                </div>
                @*<div asp-validation-summary="All"></div>*@
                <div class="mb-3">
                    <label asp-for="Title"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="col-12">
                    @if (Model.Id != 0)
                    {
                        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
                    }
                    else
                    {
                        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
                    }
                    <a asp-area="Admin" asp-controller="EmployeeType" asp-action="Index" class="btn btn-secondary" style="width:150px">
                        Back to List
                    </a>
                </div>

            </div>
        </div>

    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}