TrackBug/Areas/Employee/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using TrackBug.DataAccess.Repository.IRepository;
using TrackBug.Models;
using TrackBug.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TrackBug.Utilities;
using Microsoft.AspNetCore.Authorization;

namespace TrackBug.Areas.Employee.Controllers
{
    [Area("Employee")]
    [Authorize]
    public class ProjectController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ProjectController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
           
            //getting projects where current user is a member
            IEnumerable<ProjectMember> userProjectMemberList = _unitOfWork.ProjectMember.GetAll(u => u.ApplicationUserId == claim.Value);
            List<Project> userIsParticipantProjects = new();
            foreach (var projectMember in userProjectMemberList)
            {
                Project project = _unitOfWork.Project.GetFirstOrDefault(u => u.Id == projectMember.ProjectId);
                userIsParticipantProjects.Add(project);
            }
            List<ProjectCardVM> userIsParticipantProjectCards = new();
            foreach (var project in userIsParticipantProjects)
            {
                int numMembers = _unitOfWork.ProjectMember.GetAll(u => u.ProjectId == project.Id).Count();
                int numOpenTickets = _unitOfWork.Ticket.GetAll(u => u.ProjectId == project.Id && u.Status.Title == "Open").Count();
                userIsParticipantProjectCards.Add(new()
                {
                    Project = project,
                    NumMembers = numMembers,
                    NumOpenTickets = numOpenTickets
                });
            }

            return View(userIsParticipantProjectCards);
        }

        public IActionResult Upsert(int? id)
        {
            Project project = new();
            ViewBag.returnUrl = Request.Headers["Referer"].ToString();//save return url to redirect to after upserting is finished

            if (id == null || id == 0)//create new project
            {
                return View(project);
            }
            else // update ticket
            {
                project = _unitOfWork.Project.GetFirstOrDefault(u => u.Id == id);
                return View(project);
            }
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Project obj, string returnUrl)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (ModelState.IsValid)
            {
                if (obj.Id == 0)//create new project
                {
                    obj.ApplicationUserId = claim.Value;
                    obj.Description = HtmlUtilities.HtmlToPlainText(obj.Description);
                    _unitOfWork.Project.Add(obj);
                    await _unitOfWork.SaveAsync();
                    TempData["success"] = "Project created successfully";

                    ProjectMember projectMember = new()
                    {
                        ApplicationUserId = obj.ApplicationUserId,
                        ProjectId = obj.Id
                    };
                    _unitOfWork.ProjectMember.Add(projectMember);
                    await _unitOfWork.SaveAsync();
                }
                else //update existing project
                {
                    obj.ApplicationUserId = claim.Value;
                    obj.Description = HtmlUtilities.HtmlToPlainText(obj.Description);
                    _unitOfWork.Project.Update(obj);
                    await _unitOfWork.SaveAsync();
                    TempData["success"] = "Project updated successfully";
                }

                //return Redirect(returnUrl);
                return RedirectToAction("Details", obj.Id);
            }
            return View(obj);
        }

       
        public async Task<IActionResult> Details(int? id, string searchString, int? ticketPriority, int? ticketStatus)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            //get tickets of the current project
            var tickets = _unitOfWork.Ticket.GetAll(u => u.ProjectId == id, includeProperties: "Project,Priority,Status,ApplicationUser");
            //apply search
            if (!string.IsNullOrEmpty(searchString))
            {
                tickets = tickets.Where(u=>u.Title.Contains(searchString));
            }
            //apply priority filter if any
            if (ticketPriority!=null)
            {
                tickets = tickets.Where(u=>u.Priority.Id==ticketPriority);
            }
            //apply status filter if any
            if (ticketStatus!=null)
            {
                tickets = tickets.Where(u => u.Status.Id == ticketStatus);
            }

            ProjectDetailsVM projectDetailsVM = new()
            {
                Project = await _unitOfWork.Project.GetFirstOrDefaultAsync(u => u.Id == id, includeProperties: "ApplicationUser"),
                ProjectMembers = await _unitOfWork.ProjectMember.GetAllAsync(u => u.ProjectId == id, includeProperties: "Project,ApplicationUser"),
                PriorityList = _unitOfWork.Priority.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Title,
                    Value = i.Id.ToString()
                }),
                StatusList = _unitOfWork.Status.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Title,
                    Value = i.Id.ToString()
                }),
                Tickets = tickets,
                NumOpenTickets = _unitOfWork.Ticket.GetAll(u => u.ProjectId == id && u.Status.Title == "Open").Count(),
                NumClosedTickets = _unitOfWork.Ticket.GetAll(u => u.ProjectId == id && u.Status.Title == "Closed").Count(),

            };

            projectDetailsVM.Project.CreatedDateTimeAsString = projectDetailsVM.Project.CreatedDateTime.ToString("ddd, dd MMM yyyy, HH:mm tt");

            foreach (var ticket in projectDetailsVM.Tickets)
            {
                ticket.CreatedDateTimeAsString = ticket.CreatedDateTime.ToString("ddd, dd MMM yyyy, HH:mm tt");
                ticket.DueDateTimeAsString = ticket.DueDateTime.ToString("ddd, dd MMM yyyy, HH:mm tt");
                ticket.ApplicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == ticket.ApplicationUser.Id, includeProperties: "EmployeeType");
            }

            foreach (var member in projectDetailsVM.ProjectMembers)
            {
                member.ApplicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == member.ApplicationUserId, includeProperties: "EmployeeType");
            }

            if(projectDetailsVM.Project.ApplicationUserId == claim.Value)
            {
                projectDetailsVM.UserCanAdministerProject = true;
            }
            else
            {
                projectDetailsVM.UserCanAdministerProject = false;
            }

            return View(projectDetailsVM);
        }

        #region API CALLS

        [HttpDelete]
        public async Task<IActionResult> Delete(int? id)
        {
            var obj = await _unitOfWork.Project.GetFirstOrDefaultAsync(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting project" });
            }


            _unitOfWork.Project.Remove(obj);
            await _unitOfWork.SaveAsync();
            return Json(new { success = true, message = "Project member delete was successful" });

        }
        #endregion
    }
}

TrackBug/Areas/Employee/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using TrackBug.DataAccess.Repository.IRepository;
using TrackBug.Models;
using TrackBug.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using TrackBug.Utilities;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TrackBug.Areas.Employee.Controllers
{
    [Area("Employee")]
    [Authorize]
    public class TicketController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public TicketController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        //public async Task<IActionResult> Index()
        //{
        //    var claimsIdentity = (ClaimsIdentity)User.Identity;
        //    var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

        //    IEnumerable<Project> curUserProjectList = await _unitOfWork.Project.GetAllAsync(u => u.ApplicationUserId == claim.Value, includeProperties: "ApplicationUser");

        //    return View(curUserProjectList);
        //}
        
        public IActionResult Upsert(int? id, int? projectId)
        {
            TicketUpsertVM ticketUpsertVM = new()
            {
                Ticket = new(),
                PriorityList = _unitOfWork.Priority.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Title,
                    Value = i.Id.ToString()
                }),
                StatusList = _unitOfWork.Status.GetAll().Select(
                       i => new SelectListItem
                       {
                           Text = i.Title,
                           Value = i.Id.ToString()
                       })
            };

            ViewBag.returnUrl = Request.Headers["Referer"].ToString();//save return url to redirect to after upserting is finished

            if (id == null || id == 0)//create new ticket
            {
                if (projectId != null || projectId != 0)
                {
                    ticketUpsertVM.Ticket.ProjectId = (int)projectId;
                }
                return View(ticketUpsertVM);
            }
            else // update ticket
            {
                ticketUpsertVM.Ticket = _unitOfWork.Ticket.GetFirstOrDefault(u => u.Id == id && u.ProjectId == projectId, includeProperties: "Project,ApplicationUser,Priority,Status");
                return View(ticketUpsertVM);
            }

        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(TicketUpsertVM obj, string returnUrl)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (ModelState.IsValid)
            {
                if (obj.Ticket.Id == 0)
                {
                    obj.Ticket.ApplicationUserId = claim.Value;
                    obj.Ticket.Description = HtmlUtilities.HtmlToPlainText(obj.Ticket.Description);
                    //var project = _unitOfWork.Project.GetFirstOrDefault(u => u.Id == obj.Ticket.ProjectId);
                    //project.NumOfTickets++;
                    //_unitOfWork.Project.Update(project);
                    //await _unitOfWork.SaveAsync();

                    _unitOfWork.Ticket.Add(obj.Ticket);
                    await _unitOfWork.SaveAsync();
                    TempData["success"] = "Ticket created successfully";
                }
                else
                {
                    obj.Ticket.ApplicationUserId = claim.Value;
                    obj.Ticket.Description = HtmlUtilities.HtmlToPlainText(obj.Ticket.Description);
                    //var project = _unitOfWork.Project.GetFirstOrDefault(u => u.Id == obj.Ticket.ProjectId);
                    //var statusTitle = _unitOfWork.Status.GetFirstOrDefault(u => u.Id == obj.Ticket.StatusID).Title;
                    

                    _unitOfWork.Ticket.Update(obj.Ticket);
                    await _unitOfWork.SaveAsync();
                    TempData["success"] = "Ticket updated successfully";
                }
                return Redirect(returnUrl);

            }
            return View(obj);
        }
        
        // GET: Ticket/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _unitOfWork.Ticket
                .GetFirstOrDefaultAsync(u => u.Id == id,includeProperties: "Project,ApplicationUser,Priority,Status");
            if (ticket == null)
            {
                return NotFound();
            }
            ViewBag.returnUrl = Request.Headers["Referer"].ToString();
            return View(ticket);
        }

        // POST: Ticket/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, string returnUrl)
        {
            var ticket = await _unitOfWork.Ticket
                .GetFirstOrDefaultAsync(u => u.Id == id);
            //ticket.Project.NumOfTickets--;
            _unitOfWork.Ticket.Remove(ticket);
            await _unitOfWork.SaveAsync();
            TempData["success"] = "Ticket deleted successfully";
            return Redirect(returnUrl);
            //return RedirectToAction("Details", "Project", projectId);
        }

        public async Task<IActionResult> Details(int? id, int? projectId)
        {
            TicketVM ticketVM = new()
            {
                Ticket = await _unitOfWork.Ticket.GetFirstOrDefaultAsync(u => u.Id == id, includeProperties: "Project,Priority,Status,ApplicationUser"),
                TicketMembers = await _unitOfWork.TicketMember.GetAllAsync(u => u.Ticket.ProjectId == projectId, includeProperties: "Ticket,ApplicationUser")
            };
            ticketVM.Ticket.CreatedDateTimeAsString = ticketVM.Ticket.CreatedDateTime.ToString("ddd, dd MMM yyyy, HH:mm tt");
            ticketVM.Ticket.DueDateTimeAsString = ticketVM.Ticket.DueDateTime.ToString("ddd, dd MMM yyyy, HH:mm tt");
            foreach (var member in ticketVM.TicketMembers)
            {
                member.ApplicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == member.ApplicationUserId, includeProperties: "EmployeeType");
            }

            return View(ticketVM);
        }

        #region API CALLS
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var ticketsList = await _unitOfWork.Ticket.GetAllAsync(includeProperties: "Priority,Status,ApplicationUser");
            return Json(new { data = ticketsList });
        }
        
        #endregion
    }
}

TrackBug/Areas/Employee/Views/Ticket/Delete.cshtml
@model TrackBug.Models.Ticket

@{
    ViewData["Title"] = "Ticket Delete";
}

<h1>Ticket Delete</h1>
<hr/>
<h3>Are you sure you want to delete this ticket?</h3>
<div>
    <div class="card text-white bg-secondary">
        <h4 class="card-header"><strong>Title:</strong> @Model.Title</h4>
        <div class="card-body">
            <h4 class="card-title"><strong>Description:</strong></h4>
            <p class="card-text">@Model.Description</p>
            <h4 class="card-title"><strong>Created Date-Time:</strong></h4>
            <p class="card-text">@Model.CreatedDateTimeAsString</p>
            <h4 class="card-title"><strong>Due Date-Time:</strong></h4>
            <p class="card-text">@Model.DueDateTimeAsString</p>
            <h4 class="card-title"><strong>Priority:</strong></h4>
            <p class="card-text">@Model.Priority.Title</p>
            <h4 class="card-title"><strong>Status:</strong></h4>
            <p class="card-text">@Model.Status.Title</p>
            <h4 class="card-title"><strong>Created By:</strong></h4>
            <p class="card-text">@Model.ApplicationUser.UserName</p>
            <h4 class="card-title"><strong>Ticket is part of Project:</strong></h4>
            <a asp-area="Employee" asp-controller="Project" asp-action="Details" class="card-text text-light">@Model.Project.Title.</a>

        </div>
    </div>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="@Model.Project.Id" />
        <input type="hidden" name="returnUrl" value="@ViewBag.returnUrl" />

        <input type="submit" value="Delete" class="btn btn-danger rounded mt-2" />
        <br/>
        <a asp-area="Employee" asp-controller="Project" asp-action="Details" asp-route-id="@Model.ProjectId">
            Back to Project Details
        </a>
    </form>
</div>

TrackBug/Areas/Employee/Views/Ticket/Details.cshtml
@model TrackBug.Models.ViewModels.TicketVM
@{
    ViewData["Title"] = String.Format("{0} Details Page", Model.Ticket.Title);
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb p-3 bg-secondary">
        <li class="breadcrumb-item">
            <a asp-area="Employee" asp-controller="Project" asp-action="Index">My Projects</a>
        </li>
        <li class="breadcrumb-item">
            <a asp-area="Employee" asp-controller="Project" asp-action="Details" asp-route-id="@Model.Ticket.ProjectId">@Model.Ticket.Project.Title</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">@Model.Ticket.Title</li>
    </ol>
</nav>
<hr />
<div class="row justify-content-between">
    <div class="col-12 col-lg-7">
        <h5 class="mb-4">Ticket Overview</h5>

        <article>
            @Model.Ticket.Description
        </article>
    </div>
    <div class="col-12 col-md-4">
        <div class="card">
            <ul class="list-group list-group-flush">
                <li class="list-group-item bg-light">
                    <div class="d-flex justify-content-between">
                        <div class="text-dark"><i class="icon-text-document mr-1"></i> Created by</div>
                        <p class="card-text text-dark">@Model.Ticket.ApplicationUser.UserName</p>
                    </div>
                </li>
                <li class="list-group-item bg-light">
                    <div class="d-flex justify-content-between">
                        <div class="text-dark"><i class="icon-text-document mr-1"></i> Created date</div>
                        <p class="card-text text-dark">@Model.Ticket.CreatedDateTimeAsString</p>
                    </div>
                </li>
                <li class="list-group-item bg-light">
                    <div class="d-flex justify-content-between">
                        <div class="text-dark"><i class="icon-text-document mr-1"></i> Due date</div>
                        <p class="card-text text-dark">@Model.Ticket.DueDateTimeAsString</p>
                    </div>
                </li>
                <li class="list-group-item bg-light">
                    <div class="d-flex justify-content-between">
                        <div class="text-dark"><i class="icon-text-document mr-1"></i> Priority</div>
                        <span class="badge @Model.Ticket.Priority.BadgeColor text-uppercase">@Model.Ticket.Priority.Title</span>
                    </div>
                </li>
                <li class="list-group-item bg-light">
                    <div class="d-flex justify-content-between">
                        <div class="text-dark"><i class="icon-text-document mr-1"></i> Status</div>
                        <span class="badge bg-secondary text-uppercase">@Model.Ticket.Status.Title</span>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>



</br>
<h4> Ticket's Details Page</h4>
<hr />
<div class="row">
    <div class="col-md-5">
        @* For Ticket Details*@
        <div class="card text-white bg-secondary">
            <h4 class="card-header"><strong>Title:</strong> @Model.Ticket.Title</h4>
            <div class="card-body">
                <h4 class="card-title"><strong>Description:</strong></h4>
                <p class="card-text">@Model.Ticket.Description</p>
                <h4 class="card-title"><strong>Created Date-Time:</strong></h4>
                <p class="card-text">@Model.Ticket.CreatedDateTimeAsString</p>
                <h4 class="card-title text-danger"><strong>Due Date-Time:</strong></h4>
                <p class="card-text text-danger">@Model.Ticket.DueDateTimeAsString</p>
                <h4 class="card-title"><strong>Created By:</strong></h4>
                <p class="card-text">@Model.Ticket.ApplicationUser.Name (@Model.Ticket.ApplicationUser.Email) (add link to person's profile page?)</p>
                <h4 class="card-title"><strong>Priority:</strong></h4>
                <p class="card-text">@Model.Ticket.Priority.Title</p>
                <h4 class="card-title"><strong>Status:</strong></h4>
                <p class="card-text">@Model.Ticket.Status.Title</p>
            </div>
        </div>
    </div>
    <div class="col-md-7 pt-4">
        @* For Ticket Members area managemnt*@
        <div class="container p-3">
            <div class="row pt-4">
                <div class="col-6">
                    <h2 class="text-primary">Ticket's Members Area</h2>
                </div>
                <div class="col-6 text-end">
                    <a class="btn btn-primary rounded" asp-area="Employee" asp-controller="Ticket" asp-action="AddMember" asp-route-ticketId="@Model.Ticket.Id"><i class="bi bi-plus-circle"></i> &nbsp; Add Member</a>

                </div>
                <br />
                <table class="table table-bordered table-striped" style="width:100%">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.TicketMembers.FirstOrDefault().ApplicationUser.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TicketMembers.FirstOrDefault().ApplicationUser.Email)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TicketMembers.FirstOrDefault().ApplicationUser.EmployeeType.Title)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.TicketMembers)
                        {
                            <tr class="table-secondary">
                                <td>
                                    @Html.DisplayFor(modelItem => item.ApplicationUser.Name)
                                    @*<a asp-area="Employee" asp-controller="ProjectMember" asp-action="Details" asp-route-id="@item.Id" asp-route-projectId="@Model.Project.Id" >@Html.DisplayFor(modelItem => item.ApplicationUser.Name)</a>*@
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ApplicationUser.Email)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ApplicationUser.EmployeeType.Title)
                                </td>
                                <td class="text-end">
                                    <a onclick="ConfirmDeleteTicketMember(@item.Id)"
                                       class="btn btn-danger rounded mx-2 text-light"> <i class="bi bi-trash-fill"></i> Delete</a>
                                </td>
                                @*Modal pop for Project Member deletion*@
                                <div class="modal fade" id="ticketMemberDeleteModal">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">

                                                <h3 class="modal-title">Delete Project Member:</h3>
                                                <a class="close" onclick="CancelDelete()" data-dismiss="modal">&times;</a>
                                            </div>
                                            <div class="modal-body">
                                                <h4>Are you sure you want to delete member from the project?</h4>
                                                <input type="hidden" id="hiddenTicketMemberIdField" />
                                            </div>
                                            <div class="modal-footer">
                                                <a href="#" class="btn btn-default rounded" onclick="CancelDelete()" data-dismiss="modal">Cancel</a>
                                                <a href="#" class="btn btn-danger rounded" onclick="DeleteTicketMember()">Confirm</a>
                                            </div>

                                        </div>

                                    </div>

                                </div>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        </div>

    </div>
</div>
@section scripts{
    <script>
        var ConfirmDeleteTicketMember = function (id) {

            $("#hiddenTicketMemberIdField").val(id);
            $("#ticketMemberDeleteModal").modal('show');

        }

        var DeleteTicketMember = function () {



            var ticketMemberId = $("#hiddenTicketMemberIdField").val();

            $.ajax({

                type: 'DELETE',
                url: "/Employee/TicketMember/Delete/",
                data: { id: ticketMemberId },
                success: function (data) {
                    if (data.success) {
                        toastr.success(data.message);
                        $("#ticketMemberDeleteModal").modal("hide");
                        document.location.reload(true);
                    }
                    else {
                        toastr.error(data.message);
                        $("#ticketMemberDeleteModal").modal("hide");
                    }
                }


            })

        }
        var CancelDelete = function () {
            $("#ticketMemberDeleteModal").modal("hide");
            //$("#projectDeleteModal").modal("hide");

        }
        @*var ConfirmDeleteProject = function (id) {
            $("#hiddenProjectIdField").val(id);
            $("#projectDeleteModal").modal('show');
        }
        var DeleteProject = function () {
            var projectId = $("#hiddenProjectIdField").val();

            $.ajax({

                type: 'DELETE',
                url: "/Employee/Project/Delete/",
                data: { id: projectId },
                success: function (data) {
                    if (data.success) {
                        toastr.success(data.message);
                        $("#projectDeleteModal").modal("hide");
                        location.replace('/Employee/Project/Index');
                    }
                    else {
                        toastr.error(data.message);
                        $("#projectMemberDeleteModal").modal("hide");
                    }
                }


            })

        }*@
    </script>

}