TrackBug/Areas/Admin/Controllers/PriorityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TrackBug.DataAccess;
using TrackBug.Models;
using TrackBug.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using TrackBug.Models.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TrackBug.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Authorize(Roles = "Admin")]
    public class PriorityController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public PriorityController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Product
        public async Task<IActionResult> Index()
        {
            return View(await _unitOfWork.Priority.GetAllAsync());
        }

        //GET
        public IActionResult Upsert(int? id)
        {
            Priority priority = new();
            if (id == null || id == 0)
            {
                return View(priority);
            }
            else
            {
                // update product
                priority = _unitOfWork.Priority.GetFirstOrDefault(u => u.Id == id);
                return View(priority);
            }

            //return View(productVM);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Priority obj)
        {

            if (ModelState.IsValid)
            {
                if (obj.Id == 0)
                {
                    _unitOfWork.Priority.Add(obj);
                    await _unitOfWork.SaveAsync();
                    TempData["success"] = "Priority created successfully";
                }
                else
                {
                    _unitOfWork.Priority.Update(obj);
                    await _unitOfWork.SaveAsync();
                    TempData["success"] = "Priority updated successfully";
                }

                return RedirectToAction("Index");
            }
            return View(obj);
        }

        #region API CALLS
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var priorityList = await _unitOfWork.Priority.GetAllAsync();
            return Json(new { data = priorityList });
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int? id)
        {
            var obj = await _unitOfWork.Priority.GetFirstOrDefaultAsync(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }


            _unitOfWork.Priority.Remove(obj);
            await _unitOfWork.SaveAsync();
            return Json(new { success = true, message = "Priority delete was successful" });

        }
        #endregion


    }
}

TrackBug/Areas/Admin/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TrackBug.DataAccess;
using TrackBug.Models;
using TrackBug.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TrackBug.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Authorize(Roles = "Admin")]
    public class StatusController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public StatusController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Product
        public async Task<IActionResult> Index()
        {
            return View(await _unitOfWork.Status.GetAllAsync());
        }

        //GET
        public IActionResult Upsert(int? id)
        {
            Status status = new();


            if (id == null || id == 0)
            {
                return View(status);
            }
            else
            {
                // update product
                status = _unitOfWork.Status.GetFirstOrDefault(u => u.Id == id);
                return View(status);
            }
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Status obj)
        {

            if (ModelState.IsValid)
            {
                if (obj.Id == 0)
                {
                    _unitOfWork.Status.Add(obj);
                    await _unitOfWork.SaveAsync();
                    TempData["success"] = "Status created successfully";
                }
                else
                {
                    _unitOfWork.Status.Update(obj);
                    await _unitOfWork.SaveAsync();
                    TempData["success"] = "Status updated successfully";
                }

                return RedirectToAction("Index");
            }
            return View(obj);
        }

        #region API CALLS
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var statusList = await _unitOfWork.Status.GetAllAsync();
            return Json(new { data = statusList });
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int? id)
        {
            var obj = await _unitOfWork.Status.GetFirstOrDefaultAsync(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }


            _unitOfWork.Status.Remove(obj);
            await _unitOfWork.SaveAsync();
            return Json(new { success = true, message = "Status delete was successful" });

        }
        #endregion


    }
}

TrackBug/Areas/Employee/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using TrackBug.DataAccess.Repository.IRepository;
using TrackBug.Models;
using TrackBug.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TrackBug.Utilities;
using Microsoft.AspNetCore.Authorization;

namespace TrackBug.Areas.Employee.Controllers
{
    [Area("Employee")]
    [Authorize]
    public class ProjectController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ProjectController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
           
            //getting projects where current user is a member
            IEnumerable<ProjectMember> userProjectMemberList = _unitOfWork.ProjectMember.GetAll(u => u.ApplicationUserId == claim.Value);
            List<Project> userIsParticipantProjects = new();
            foreach (var projectMember in userProjectMemberList)
            {
                Project project = _unitOfWork.Project.GetFirstOrDefault(u => u.Id == projectMember.ProjectId);
                userIsParticipantProjects.Add(project);
            }
            List<ProjectCardVM> userIsParticipantProjectCards = new();
            foreach (var project in userIsParticipantProjects)
            {
                int numMembers = _unitOfWork.ProjectMember.GetAll(u => u.ProjectId == project.Id).Count();
                int numOpenTickets = _unitOfWork.Ticket.GetAll(u => u.ProjectId == project.Id && u.Status.Title == "Open").Count();
                userIsParticipantProjectCards.Add(new()
                {
                    Project = project,
                    NumMembers = numMembers,
                    NumOpenTickets = numOpenTickets
                });
            }

            return View(userIsParticipantProjectCards);
        }

        public IActionResult Upsert(int? id)
        {
            Project project = new();
            ViewBag.returnUrl = Request.Headers["Referer"].ToString();//save return url to redirect to after upserting is finished

            if (id == null || id == 0)//create new project
            {
                return View(project);
            }
            else // update ticket
            {
                project = _unitOfWork.Project.GetFirstOrDefault(u => u.Id == id);
                return View(project);
            }
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Project obj, string returnUrl)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (ModelState.IsValid)
            {
                if (obj.Id == 0)//create new project
                {
                    obj.ApplicationUserId = claim.Value;
                    obj.Description = HtmlUtilities.HtmlToPlainText(obj.Description);
                    _unitOfWork.Project.Add(obj);
                    await _unitOfWork.SaveAsync();
                    TempData["success"] = "Project created successfully";

                    ProjectMember projectMember = new()
                    {
                        ApplicationUserId = obj.ApplicationUserId,
                        ProjectId = obj.Id
                    };
                    _unitOfWork.ProjectMember.Add(projectMember);
                    await _unitOfWork.SaveAsync();
                }
                else //update existing project
                {
                    obj.ApplicationUserId = claim.Value;
                    obj.Description = HtmlUtilities.HtmlToPlainText(obj.Description);
                    _unitOfWork.Project.Update(obj);
                    await _unitOfWork.SaveAsync();
                    TempData["success"] = "Project updated successfully";
                }

                //return Redirect(returnUrl);
                return RedirectToAction("Details", obj.Id);
            }
            return View(obj);
        }

       
        public async Task<IActionResult> Details(int? id, string searchString, int? ticketPriority, int? ticketStatus)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            //get tickets of the current project
            var tickets = _unitOfWork.Ticket.GetAll(u => u.ProjectId == id, includeProperties: "Project,Priority,Status,ApplicationUser");
            //apply search
            if (!string.IsNullOrEmpty(searchString))
            {
                tickets = tickets.Where(u=>u.Title.Contains(searchString));
            }
            //apply priority filter if any
            if (ticketPriority!=null)
            {
                tickets = tickets.Where(u=>u.Priority.Id==ticketPriority);
            }
            //apply status filter if any
            if (ticketStatus!=null)
            {
                tickets = tickets.Where(u => u.Status.Id == ticketStatus);
            }

            ProjectDetailsVM projectDetailsVM = new()
            {
                Project = await _unitOfWork.Project.GetFirstOrDefaultAsync(u => u.Id == id, includeProperties: "ApplicationUser"),
                ProjectMembers = await _unitOfWork.ProjectMember.GetAllAsync(u => u.ProjectId == id, includeProperties: "Project,ApplicationUser"),
                PriorityList = _unitOfWork.Priority.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Title,
                    Value = i.Id.ToString()
                }),
                StatusList = _unitOfWork.Status.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Title,
                    Value = i.Id.ToString()
                }),
                Tickets = tickets,
                NumOpenTickets = _unitOfWork.Ticket.GetAll(u => u.ProjectId == id && u.Status.Title == "Open").Count(),
                NumClosedTickets = _unitOfWork.Ticket.GetAll(u => u.ProjectId == id && u.Status.Title == "Closed").Count(),

            };

            projectDetailsVM.Project.CreatedDateTimeAsString = projectDetailsVM.Project.CreatedDateTime.ToString("ddd, dd MMM yyyy, HH:mm tt");

            foreach (var ticket in projectDetailsVM.Tickets)
            {
                ticket.CreatedDateTimeAsString = ticket.CreatedDateTime.ToString("ddd, dd MMM yyyy, HH:mm tt");
                ticket.DueDateTimeAsString = ticket.DueDateTime.ToString("ddd, dd MMM yyyy, HH:mm tt");
                ticket.ApplicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == ticket.ApplicationUser.Id, includeProperties: "EmployeeType");
            }

            foreach (var member in projectDetailsVM.ProjectMembers)
            {
                member.ApplicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == member.ApplicationUserId, includeProperties: "EmployeeType");
            }

            if(projectDetailsVM.Project.ApplicationUserId == claim.Value)
            {
                projectDetailsVM.UserCanAdministerProject = true;
            }
            else
            {
                projectDetailsVM.UserCanAdministerProject = false;
            }

            return View(projectDetailsVM);
        }

        #region API CALLS

        [HttpDelete]
        public async Task<IActionResult> Delete(int? id)
        {
            var obj = await _unitOfWork.Project.GetFirstOrDefaultAsync(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting project" });
            }


            _unitOfWork.Project.Remove(obj);
            await _unitOfWork.SaveAsync();
            return Json(new { success = true, message = "Project member delete was successful" });

        }
        #endregion
    }
}

TrackBug/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TrackBug</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/bootswatchPulseTheme.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />
    <script src="https://cdn.tiny.cloud/1/ua65d8knfrx5xg9mc0f7j6wo10x1w90nx5hvdwm8fm2cwtgf/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        @*<nav class="navbar navbar-expand-lg navbar-dark bg-primary navbar-toggleable-sm border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TrackBug</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>*@
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Employee" asp-controller="Home" asp-action="Index">TrackBug</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Admin"))
                         {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin area</a>
                                <div class="dropdown-menu">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="EmployeeType" asp-action="Index">Employee Types</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Priority" asp-action="Index">Priority Types</a>

                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Status" asp-action="Index">Status Types</a>

                                </div>
                            </li>
                        }

                        <li class="nav-item">
                                <a class="nav-link" asp-area="Employee" asp-controller="Project" asp-action="Index">My Projects</a>
                            </li>

                    </ul>
                    <partial name="_LoginPartial" />

                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />

            @RenderBody()
        </main>
    </div>

    @*<footer class="footer text-muted">
        <div class="container">
            &copy; 2022 - TrackBug - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.11.2/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TrackBug/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>

}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}